// BlueprintGeneratedClass BPL_ThrowableHelpers.BPL_ThrowableHelpers_C
// Size: 0x28 (Inherited: 0x28)
struct UBPL_ThrowableHelpers_C : UBlueprintFunctionLibrary {

	void MyCheckForPawnsInTheWay(struct TArray<struct FHitResult> HitResults, bool PenetratePawns, struct UObject* __WorldContext, bool OnlyPawns); // Function BPL_ThrowableHelpers.BPL_ThrowableHelpers_C.MyCheckForPawnsInTheWay // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void GetMyDamageOrigin(struct AActor* ExplodingActor, struct UObject* __WorldContext, struct FVector DamageOrigin); // Function BPL_ThrowableHelpers.BPL_ThrowableHelpers_C.GetMyDamageOrigin // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void MyMultiLineTrace(struct FVector Start, struct FVector End, enum class ETraceTypeQuery TraceChannel, struct TArray<struct AActor*> ActorsToIgnore, struct UObject* __WorldContext, struct TArray<struct FHitResult> MyHits, bool IsBlockingHit); // Function BPL_ThrowableHelpers.BPL_ThrowableHelpers_C.MyMultiLineTrace // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void GetMyDamageTargets(struct AActor* MyActor, struct UObject* __WorldContext, struct TArray<struct FVector> MyTargets); // Function BPL_ThrowableHelpers.BPL_ThrowableHelpers_C.GetMyDamageTargets // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void CustomLineOfSightCheck(struct AActor* Victim, struct AActor* ExplodingActor, enum class BPE_CustomLoSCheckType LoSCheckType, bool PenetratePawns, enum class ETraceTypeQuery TraceChannel, struct UObject* __WorldContext, bool IsInLineOfSight); // Function BPL_ThrowableHelpers.BPL_ThrowableHelpers_C.CustomLineOfSightCheck // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void ClusterGetSpreadZOffset(float CurrentDistanceSquared, float StartingDistanceSquared, float MaxZOffset, struct UObject* __WorldContext, float SpreadZOffset); // Function BPL_ThrowableHelpers.BPL_ThrowableHelpers_C.ClusterGetSpreadZOffset // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void ClusterTelegraphSpreading(struct UNiagaraComponent* NiagaraPS, struct FVector OriginLocation, struct FVector TargetLocation, float DeltaTime, float InterpSpeed, float MaxZOffset, float CurrentZOffset, struct UObject* __WorldContext, bool TargetReached, float NewZOffset); // Function BPL_ThrowableHelpers.BPL_ThrowableHelpers_C.ClusterTelegraphSpreading // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void ClusterGetSpawnLocation(struct UObject* ContextObject, struct FVector OriginLocation, struct FVector TargetLocation, float TargetDepthCheck, float MinSpreadDistance, struct UObject* __WorldContext, bool CanSpawn, struct FVector ClusterSpawnLocation); // Function BPL_ThrowableHelpers.BPL_ThrowableHelpers_C.ClusterGetSpawnLocation // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
};

