// BlueprintGeneratedClass BPL_ShopHelpers.BPL_ShopHelpers_C
// Size: 0x28 (Inherited: 0x28)
struct UBPL_ShopHelpers_C : UBlueprintFunctionLibrary {

	void CanBuyCharacterCustomizationOrArmorSet(struct FHWShopItem Item, struct UObject* __WorldContext, bool CanBuy); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.CanBuyCharacterCustomizationOrArmorSet // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void IsItemOutOfStock(struct FHWShopItem Item, struct UObject* __WorldContext, bool OutOfStock); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.IsItemOutOfStock // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void GetShopItemGenericDescriptionByType(enum class BPE_ShopItemType Type, enum class EHWWeaponPartType PartType, struct UObject* __WorldContext, struct FText Description); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.GetShopItemGenericDescriptionByType // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void Load Default Shop Item Image(enum class BPE_ShopItemType Type, struct FName ID, enum class EHWFaction Faction, enum class EHWRarity Rarity, struct UObject* __WorldContext, struct UTexture2D* Image); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.Load Default Shop Item Image // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void GetOfferText(int32_t MaxPurchase, struct FString ShopItemId, struct UObject* __WorldContext, struct FText Text, struct FLinearColor BackgroundColor, enum class BPE_UIColors TextColor, bool IsOutOfStock); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.GetOfferText // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void GetDetailTitleText(struct FHWShopItem Item, int32_t Index, struct UObject* __WorldContext, struct FText Text); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.GetDetailTitleText // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void IsOwnedByRewardIndex(struct FHWShopItem Item, int32_t RewardIndex, struct UObject* __WorldContext, bool Owned); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.IsOwnedByRewardIndex // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void Get Campaign Timer(struct FDateTime ExpiryDateTime, struct UObject* __WorldContext, bool IsExpired, bool LessThanHourRemaining, struct FText TimerText); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.Get Campaign Timer // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void IsOwned(struct FHWShopItem Item, struct UObject* __WorldContext, bool Owned); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.IsOwned // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void IsPurchased(struct FHWShopItem Item, struct UObject* __WorldContext, bool Purchased); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.IsPurchased // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void GetShopItemName(struct FHWShopItem Item, struct UObject* __WorldContext, struct FText Name); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.GetShopItemName // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void GetSubsectionById(struct FString SubsectionId, struct UObject* __WorldContext, struct FHWShopSubsection Subsection); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.GetSubsectionById // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void IsFree(struct FHWShopItem Item, struct UObject* __WorldContext, bool IsFree); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.IsFree // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void GetShopRewardName(struct FHWShopItem Item, int32_t Index, bool DoShowQuantity, struct UObject* __WorldContext, struct FText Name); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.GetShopRewardName // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void GetBPCodeDescription(enum class EHWCraftingParameterGroup Type, struct UObject* __WorldContext, struct FText CodeDescription); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.GetBPCodeDescription // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void IsBundle(struct FHWShopItem Item, struct UObject* __WorldContext, bool Bundle); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.IsBundle // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void GetShopItemType(struct FHWShopItem Item, int32_t ItemIndex, struct UObject* __WorldContext, enum class BPE_ShopItemType Type, enum class EHWFaction Faction); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.GetShopItemType // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void Is3DShopItem(struct FHWShopItem Item, int32_t RewardIndex, struct UObject* __WorldContext, bool Result); // Function BPL_ShopHelpers.BPL_ShopHelpers_C.Is3DShopItem // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
};

