// BlueprintGeneratedClass BPL_MenuHelpers.BPL_MenuHelpers_C
// Size: 0x28 (Inherited: 0x28)
struct UBPL_MenuHelpers_C : UBlueprintFunctionLibrary {

	void FriendInvitePending(struct FString PlayerId, struct UObject* __WorldContext, bool Result); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.FriendInvitePending // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void ShowRewardsPopup(struct FText Title, struct FText Message, struct FString MissionId, bool CanReroll, bool CanGoToItem, struct TArray<struct FHWReward> Rewards, struct UObject* __WorldContext, struct UWBP_Rewards_Popup_C* Popup); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.ShowRewardsPopup // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void GetSelectedWeaponVariationIndex(struct UHWArmoryWeaponModel* WeaponModel, struct UObject* __WorldContext, int32_t Index); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.GetSelectedWeaponVariationIndex // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void IsViewLockedForPlayer(enum class BPE_UIView View, struct UObject* __WorldContext, bool IsLocked, int32_t LevelRequired); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.IsViewLockedForPlayer // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure|Const) // @ game+0x13c4ca0
	void IsFriendOfPlayerByName(struct FString Name, struct UObject* __WorldContext, bool IsFriend); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.IsFriendOfPlayerByName // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void IsInMyParty(struct FString PlayerId, struct UObject* __WorldContext, bool Result); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.IsInMyParty // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void IsBlockedPlayer(struct FString PlayerId, struct UObject* __WorldContext, bool Result); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.IsBlockedPlayer // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void IsFriendOfPlayer(struct FString PlayerId, struct UObject* __WorldContext, bool Result); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.IsFriendOfPlayer // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void GetDefaultLoadoutContents(struct UObject* __WorldContext, struct FName ArmorSetId, struct FName Item1, struct FName Item2, struct FName DroneAbility, struct FName ArmorFeature, struct FName Character); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.GetDefaultLoadoutContents // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void Reload Main MenuUI(struct UObject* __WorldContext); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.Reload Main MenuUI // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	bool HasRewards(struct FHWFetchRewardsResponse HWFetchRewardsResponse, struct UObject* __WorldContext); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.HasRewards // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void GetLootTypeIcon(struct UHWLootItem* Item, struct UObject* __WorldContext, struct UTexture2D* Icon); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.GetLootTypeIcon // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void Get Loot Box Name(enum class EHWFaction Corporation, enum class EHWRarity Rarity, int32_t Size, struct UObject* __WorldContext, struct FText Name); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.Get Loot Box Name // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void GetMenuTutorial(struct UObject* __WorldContext, struct TScriptInterface<None> TutorialLayer); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.GetMenuTutorial // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void Get View Controller(struct UObject* __WorldContext, struct TScriptInterface<None> Controller); // Function BPL_MenuHelpers.BPL_MenuHelpers_C.Get View Controller // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
};

