// BlueprintGeneratedClass BPL_ItemHelpers.BPL_ItemHelpers_C
// Size: 0x28 (Inherited: 0x28)
struct UBPL_ItemHelpers_C : UBlueprintFunctionLibrary {

	void AddDetectionStatusWithCheck(struct AActor* Victim, struct AActor* Instigator, enum class EHWDetectionStatus DetectionStatus, float Duration, bool AddToTeam, int32_t Team, struct FString SourceSessionId, bool DetectedByDrone, struct AActor* SourceActor, struct UObject* __WorldContext, bool DetectionApplied); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.AddDetectionStatusWithCheck // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void IsLocalTeamEnemy(struct AActor* Item, int32_t ItemTeam, bool IsHacked, struct AHWPlayerController* HackedController, struct UObject* __WorldContext, bool IsEnemy); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.IsLocalTeamEnemy // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void ReduceBlastPaddingArmorDamage(float InputDamage, struct AActor* Victim, struct UObject* __WorldContext, float OutputDamage); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.ReduceBlastPaddingArmorDamage // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void DealGradientDamageToDestructible(struct UHWDestructibleComponent* VictimDestructibleComponent, struct AActor* DamageDealingActor, float MinRange, float MaxRange, float MaxDamage, float MinDamage, enum class EHWDamageType DamageType, struct UObject* __WorldContext); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.DealGradientDamageToDestructible // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void DealCustomDamage(struct AActor* DamageDealingActor, struct AHWHumanCharacter* Victim, enum class EHWDamageType DamageType, enum class EHWBodypart Bodypart, bool CanCauseBleeding, float ArmorDamage, float HealthDamage, struct UObject* __WorldContext); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.DealCustomDamage // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void DealSimpleGradientEnviroDamage(struct AActor* DamageDealingActor, struct FName SourceName, struct AHWHumanCharacter* Victim, enum class EHWDamageType DamageType, enum class EHWBodypart Bodypart, bool CanCauseBleeding, float MinRange, float MaxRange, float MaxDamage, float MinDamage, struct UObject* __WorldContext); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.DealSimpleGradientEnviroDamage // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void DealSimpleEnviroDamage(struct AActor* DamageDealingActor, struct FName SourceName, struct AHWHumanCharacter* Victim, enum class EHWDamageType DamageType, enum class EHWBodypart Bodypart, bool CanCauseBleeding, float Damage, struct UObject* __WorldContext); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.DealSimpleEnviroDamage // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void DealSimpleGradientDamage(struct AActor* DamageDealingActor, struct AHWHumanCharacter* Victim, enum class EHWDamageType DamageType, enum class EHWBodypart Bodypart, bool CanCauseBleeding, float MinRange, float MaxRange, float MaxDamage, float MinDamage, struct UObject* __WorldContext); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.DealSimpleGradientDamage // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void DealSimpleDamage(struct AActor* DamageDealingActor, struct AHWHumanCharacter* Victim, enum class EHWDamageType DamageType, enum class EHWBodypart Bodypart, bool CanCauseBleeding, float Damage, enum class EHWDamageDealerType DamageDealerType, struct UObject* __WorldContext); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.DealSimpleDamage // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void CanItemDamageTeam(struct AActor* Source, struct AActor* Target, struct UObject* __WorldContext, bool CanDamage); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.CanItemDamageTeam // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void DamageDestructibleComponent(float DamageValue, struct UHWDestructibleComponent* VictimComponent, struct AActor* ExplodingActor, struct UCurveFloat* DamageFalloff, struct UObject* __WorldContext); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.DamageDestructibleComponent // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void SelectFurthestHit(struct TArray<struct FHitResult> Hits, struct AActor* Victim, struct UObject* __WorldContext, struct FHitResult Hit, bool HitBlocked); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.SelectFurthestHit // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void GetInjuryType(float Distance, float FatalRange, float SevereRange, float LightRange, struct UObject* __WorldContext, char InjuryType); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.GetInjuryType // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void GetAnalyticsIDs(struct AActor* ExplodingActor, struct UObject* __WorldContext, struct FString SessionId, int32_t ItemAnalyticsID); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.GetAnalyticsIDs // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	void GetDamageTargets(struct AActor* Target, struct UObject* __WorldContext, struct TArray<struct FVector> Targets); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.GetDamageTargets // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	bool ExplosionLineTrace(struct FVector Start, struct FVector End, struct TArray<struct AActor*> ActorsToIgnore, struct UObject* __WorldContext, struct TArray<struct FHitResult> OutHits); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.ExplosionLineTrace // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
	void GetDamageOrigin(struct AActor* ExplodingActor, struct UObject* __WorldContext, struct FVector DamageOrigin); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.GetDamageOrigin // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x13c4ca0
	bool ExplosionLineOfSightCheck(struct AActor* Victim, struct AActor* ExplodingActor, struct UObject* __WorldContext); // Function BPL_ItemHelpers.BPL_ItemHelpers_C.ExplosionLineOfSightCheck // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x13c4ca0
};

